import assert from 'node:assert/strict';
import {test} from 'node:test';
import fs from 'node:fs';
import vm from 'node:vm';
import { createRequire } from 'node:module';
const root=process.cwd();
const require=createRequire(root+'/package.json'); const ts=require('typescript');
const calendar=await import(root+'/lib/workspace-calendar.ts'); const reportExport=await import(root+'/lib/report-export.ts');
const tick=()=>new Promise(r=>setImmediate(r));
function harness(filename, initialNow=Date.now()){
 let now=typeof initialNow==='string'?Date.parse(initialNow):initialNow;const timers=[];
 class ReviewDate extends Date {constructor(...args){super(...(args.length?args:[now]));}static now(){return now;}}
 const slots=[];const effects=[];let cursor=0;let pending=[];
 const changed=(a,b)=>!a||!b||a.length!==b.length||b.some((v,i)=>!Object.is(v,a[i]));
 const react={createElement:(type,props,...children)=>({type,props:{...props,children}}),
  useState(initial){let i=cursor++;if(!slots[i])slots[i]={value:typeof initial==='function'?initial():initial};return[slots[i].value,value=>{slots[i].value=typeof value==='function'?value(slots[i].value):value;}];},
  useRef(initial){let i=cursor++;return slots[i] ||= {current:initial};},
  useMemo(fn,deps){let i=cursor++;if(changed(slots[i]?.deps,deps))slots[i]={deps,value:fn()};return slots[i].value;},
  useCallback(fn,deps){return react.useMemo(()=>fn,deps);},
  useEffect(fn,deps){let i=cursor++;if(changed(effects[i]?.deps,deps))pending.push(()=>{effects[i]?.cleanup?.();effects[i]={deps,cleanup:fn()};});},
 };
 const state={user:{uid:'review-user'},workspace:{currentOrganizationId:'org-A',ready:true,loading:false,membership:{role:'ADMIN'},canWrite:true},app:{settings:{timezone:'America/New_York',currency:'USD',leadSources:[{name:'Website'}],pipelineStages:['New','Won','Lost']},settingsLoading:false,leads:[],clients:[],deals:[],tasks:[],activities:[],users:[]}};
 const requests=[];const loaders={listSalesPage:(...args)=>new Promise((resolve,reject)=>requests.push({kind:'sales',args,resolve,reject})),getSalesKpiMetrics:(...args)=>new Promise((resolve,reject)=>requests.push({kind:'salesKpi',args,resolve,reject})),loadReportData:(...args)=>new Promise((resolve,reject)=>requests.push({kind:'report',args,resolve,reject})),loadDashboardMetrics:(...args)=>new Promise((resolve,reject)=>requests.push({kind:'dashboard',args,resolve,reject})),getPipelineStageSummaries:(...args)=>new Promise((resolve,reject)=>requests.push({kind:'pipeline',args,resolve,reject}))};
 const generic=new Proxy({}, {get:(_t,key)=>key==='__esModule'?true:key==='default'?function Component(){}:function Component(){}});
 const dependencies={react:{...react,default:react},'@/context/AppContext':{useApp:()=>state.app},'@/context/AuthContext':{useAuth:()=>({user:state.user})},'@/context/WorkspaceContext':{useWorkspace:()=>state.workspace},'@/lib/workspace-calendar':calendar,'@/lib/report-export':reportExport,'@/lib/repositories/reports':loaders,'@/lib/repositories/dashboard':{...loaders,invalidateDashboardMetrics:()=>{}},'@/lib/repositories/deals':{...loaders,invalidatePipelineStageSummaryRequests:()=>{}},'@/lib/deal-workflow':{DEAL_STAGES:['New','Won','Lost'],DEAL_ACTIVE_STAGES:['New']},'@/lib/formatting':{formatCurrency:(v,c)=>`${c} ${v}`,formatCurrencyParts:v=>({beforeDecimal:String(v)})},'@/lib/repositories/pagination':{firestoreQueryErrorMessage:(_e,m)=>m},'@/lib/kpi-preferences':{organizationPreferenceKey:(a,b)=>a+b,readKpiPreference:(_s,_k,defaults)=>defaults},'@/lib/dashboard-kpis':{DEFAULT_DASHBOARD_KPI_IDS:['deals.open'],KPI_REGISTRY:[],getKpiDefinition:()=>({label:'open',icon:()=>{},format:'number'}),readDashboardKpiPreference:()=>['deals.open']},'@/lib/task-utils':{isFollowUpTask:()=>false}};
 dependencies['@/lib/repositories/sales']={...loaders,SALES_PAGE_SIZE:25};
 dependencies['@/lib/repositories/pagination'].appendUniqueById=(a,b)=>[...a,...b];
 dependencies['@/lib/repositories/pagination'].userFacingErrorMessage=(_e,message)=>message;
 const window={localStorage:{getItem:()=>null,setItem:()=>{}},setTimeout:()=>1,clearTimeout:()=>{},setInterval:fn=>{timers.push(fn);return timers.length;},clearInterval:()=>{},requestAnimationFrame:()=>1,cancelAnimationFrame:()=>{},addEventListener:()=>{},removeEventListener:()=>{}};
 const document={body:{style:{}},addEventListener:()=>{},removeEventListener:()=>{}};
 const mod={exports:{}};
 const compiled=ts.transpileModule(fs.readFileSync(root+'/'+filename,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.React}}).outputText;
 vm.runInNewContext(compiled,{module:mod,exports:mod.exports,require:name=>dependencies[name]??generic,React:react,window,document,console,Date:ReviewDate,URL,Blob,Intl,Error,JSON,Set,Map});
 return {state,requests,slots,advanceTime(value){now=Date.parse(value);timers.forEach(fn=>fn());},render(){cursor=0;pending=[];return mod.exports.default();},commit(){pending.splice(0).forEach(f=>f());},dispose(){effects.forEach(e=>e?.cleanup?.());}};
}
const walk=(tree,predicate)=>{if(!tree||typeof tree!=='object')return[];if(Array.isArray(tree))return tree.flatMap(item=>walk(item,predicate));return [...(predicate(tree)?[tree]:[]),...Object.values(tree.props??{}).flatMap(value=>walk(value,predicate))];};
const text=tree=>typeof tree==='string'||typeof tree==='number'?String(tree):Array.isArray(tree)?tree.map(text).join(''):tree&&typeof tree==='object'?text(tree.props?.children):'';
test('actual metric pages isolate scopes, reconcile render boundaries, retain pagination and roll workspace dates safely', async () => {
const report={totalLeads:2,qualifiedLeads:1,clients:3,convertedLeads:1,activeDeals:4,totalSales:54321,transactions:1,amountPaid:10,outstanding:20,pipelineValue:30,wonDeals:1,lostDeals:1,wonVsLost:{won:1,lost:1},pipelineByStage:{New:30},leadsBySource:{Website:2},salesBySource:{CLIENT:1},salesByPaymentStatus:{PAID:1}};
const h=harness('app/reports/page.tsx');let tree=h.render();h.commit();assert.equal(h.requests.length,1);h.requests[0].resolve(report);await tick();tree=h.render();h.commit();assert.equal(walk(tree,n=>n.props?.label==='Total Sales')[0].props.value,'USD 54321');
const exportButton=()=>walk(tree,n=>n.props?.onClick&&text(n).includes('Export CSV'))[0];assert.equal(exportButton().props.disabled,false);exportButton().props.onClick();tree=h.render();assert.equal(walk(tree,n=>n.props?.title==='Export report?')[0].props.open,true);
h.state.workspace.membership={role:'USER'};tree=h.render();assert.equal(walk(tree,n=>n.props?.label==='Total Sales').length,0);assert.equal(exportButton().props.disabled,true);assert.equal(walk(tree,n=>n.props?.title==='Export report?')[0].props.open,false);h.commit();assert.equal(h.requests.length,2);
h.state.workspace.currentOrganizationId='org-B';tree=h.render();h.commit();h.requests[1].resolve({...report,totalSales:888});await tick();tree=h.render();assert.equal(walk(tree,n=>n.props?.label==='Total Sales').length,0);h.requests[2].resolve({...report,totalSales:777});await tick();tree=h.render();h.commit();assert.equal(walk(tree,n=>n.props?.label==='Total Sales')[0].props.value,'USD 777');
const select=walk(tree,n=>n.type==='select')[0];select.props.onChange({target:{value:'LastMonth'}});tree=h.render();assert.equal(walk(tree,n=>n.props?.label==='Total Sales').length,0);h.commit();h.requests[3].reject(new Error('Synthetic failed refresh'));await tick();tree=h.render();assert.equal(walk(tree,n=>n.props?.label==='Total Sales').length,0);assert.equal(exportButton().props.disabled,true);assert.ok(text(tree).includes('Unable to load reports'));h.dispose();
console.log('Reports actual-page scope/export/role/late-result/error assertions passed');
const d=harness('app/page.tsx');tree=d.render();d.commit();const dashboard=d.requests.find(r=>r.kind==='dashboard');const pipeline=d.requests.find(r=>r.kind==='pipeline');dashboard.resolve({values:{'deals.open':123},failedKpis:[]});pipeline.resolve({New:{count:123,value:999}});await tick();tree=d.render();d.commit();assert.equal(walk(tree,n=>n.props?.id==='deals.open')[0].props.value,123);assert.ok(walk(tree,n=>n.props?.stageSummary)[0]);
d.state.workspace.membership={role:'USER'};tree=d.render();assert.equal(walk(tree,n=>n.props?.id==='deals.open')[0].props.value,undefined);assert.equal(walk(tree,n=>n.props?.stageSummary).length,0);d.commit();
d.state.workspace.currentOrganizationId='org-B';tree=d.render();d.commit();const second=d.requests.filter(r=>r.kind==='dashboard')[1];second.resolve({values:{'deals.open':456},failedKpis:[]});await tick();tree=d.render();assert.equal(walk(tree,n=>n.props?.id==='deals.open')[0].props.value,undefined);d.dispose();console.log('Dashboard actual-page role/workspace/late-result assertions passed');
const s=harness('app/sales/page.tsx');tree=s.render();s.commit();
const sale={id:'sale-old',saleDate:'2026-10-07',saleNumber:'SYNTHETIC-OLD',customerName:'Review',source:'CLIENT',items:[],total:15,paymentStatus:'PAID',status:'ACTIVE'};
s.requests.find(r=>r.kind==='sales').resolve({items:[sale],nextCursor:{id:'next'},hasMore:true});
s.requests.find(r=>r.kind==='salesKpi').resolve({total:15,transactionCount:1,amountPaid:15,balance:0,average:15,paid:1,partial:0,unpaid:0,deal:0,client:1,walkIn:0,unavailable:[]});await tick();tree=s.render();s.commit();assert.ok(text(tree).includes('SYNTHETIC-OLD'));
const loadMore=walk(tree,n=>n.props?.onClick&&text(n)==='Load More Sales')[0];loadMore.props.onClick();s.requests.filter(r=>r.kind==='sales').at(-1).reject(new Error('Synthetic pagination failure'));await tick();tree=s.render();console.log('Sales prior-row still visible after page failure:',text(tree).includes('SYNTHETIC-OLD'));assert.ok(text(tree).includes('SYNTHETIC-OLD'),'Pagination failure must retain already loaded same-scope Sales rows');
s.state.workspace.membership={role:'USER'};tree=s.render();assert.ok(!text(tree).includes('SYNTHETIC-OLD'));assert.equal(walk(tree,n=>n.props?.label==='Total Sales')[0].props.unavailable,true);s.commit();
s.state.workspace.currentOrganizationId='org-B';tree=s.render();s.commit();s.requests.filter(r=>r.kind==='sales').at(-2).resolve({items:[{...sale,saleNumber:'LATE-OLD-SCOPE'}],nextCursor:null,hasMore:false});s.requests.filter(r=>r.kind==='salesKpi').at(-2).resolve({total:888,transactionCount:1,amountPaid:15,balance:0,average:15,paid:1,partial:0,unpaid:0,deal:0,client:1,walkIn:0,unavailable:[]});await tick();tree=s.render();assert.ok(!text(tree).includes('LATE-OLD-SCOPE'));s.dispose();console.log('Sales actual-page role/workspace/late-result assertions passed');
const midnight=harness('app/sales/page.tsx','2026-03-01T04:59:00Z');tree=midnight.render();midnight.commit();assert.equal(midnight.requests.find(r=>r.kind==='sales').args[2].dateFrom,'2026-02-28');midnight.advanceTime('2026-03-01T05:01:00Z');tree=midnight.render();midnight.commit();tree=midnight.render();midnight.commit();assert.equal(midnight.requests.filter(r=>r.kind==='sales').at(-1).args[2].dateFrom,'2026-03-01');
walk(tree,n=>n.type==='select'&&n.props['aria-label']==='Date range')[0].props.onChange({target:{value:'CUSTOM'}});tree=midnight.render();midnight.commit();const requestCount=midnight.requests.length;midnight.advanceTime('2026-03-02T05:01:00Z');tree=midnight.render();midnight.commit();tree=midnight.render();midnight.commit();assert.equal(midnight.requests.length,requestCount);midnight.dispose();console.log('Sales workspace midnight rollover and CUSTOM retention assertions passed');
const defaults=harness('app/page.tsx','2026-03-01T01:00:00Z');defaults.state.app.settings.timezone='UTC';defaults.state.app.settingsLoading=true;tree=defaults.render();defaults.commit();defaults.state.app.settings.timezone='America/New_York';defaults.state.app.settingsLoading=false;tree=defaults.render();defaults.commit();tree=defaults.render();defaults.commit();walk(tree,n=>n.type==='button'&&n.props['aria-label']?.startsWith('Dashboard time range:'))[0].props.onClick();tree=defaults.render();walk(tree,n=>n.type==='button'&&n.props.role==='option'&&text(n).includes('Custom'))[0].props.onClick();tree=defaults.render();defaults.commit();let dateInputs=walk(tree,n=>n.type==='input'&&n.props.type==='date');assert.equal(dateInputs[1].props.value,'2026-02-28');dateInputs[1].props.onChange({target:{value:'2026-02-20'}});tree=defaults.render();defaults.commit();defaults.state.app.settings.timezone='Asia/Manila';tree=defaults.render();defaults.commit();tree=defaults.render();dateInputs=walk(tree,n=>n.type==='input'&&n.props.type==='date');assert.equal(dateInputs[1].props.value,'2026-02-20');defaults.dispose();console.log('Dashboard asynchronously loaded workspace defaults and manual date retention assertions passed');

});
